name: Java API Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/java-api/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/java-api/**'

env:
  WORKING_DIRECTORY: services/java-api

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Validate Checkstyle
      run: ./mvnw validate

    - name: Run Tests
      run: ./mvnw test

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests
